name: Python test
on: [push]

jobs:
  ci-tests:
    strategy:
      fail-fast: false
      matrix:
        version: ["2.7","3.9"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkouut code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install Python
      run: sudo apt update && sudo apt install -y python${{ matrix.version }}
    
    - name: Check PY version
      run: |
        python${{ matrix.version }}
    
    -name: Run code
      run: |
        python${{ matrix.version }} draw.py